# Generated by Django 3.2.13 on 2023-03-09 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230309_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_verifield_email',
            new_name='is_verified_email',
        ),
    ]
